registry:
    image: registry:2
    ports:
    - 5000:5000
    volumes:
    - /registry:/var/lib/registry
    hostname: registry
    container_name: registry

HyperRegUI:
  image: hyper/docker-registry-web
  ports:
    - "8080:8080"
  links:
    - registry
  environment:
   REGISTRY_HOST: 192.168.99.100
  hostname: reg-webui
  container_name: reg-webui

#kwkRegUI:
#   image: konradkleine/docker-registry-frontend
#   ports:
#    - "80"
#   environment:
#    - ENV_DOCKER_REGISTRY_HOST=192.168.99.100
#    - ENV_DOCKER_REGISTRY_PORT=5000
#   links:
#    - registry
    
