gapi:
    hostname: graphite-api
    container_name: graphite-api
    dns: 127.0.0.1
    image: qnib/graphite-api
    environment:
     - DC_NAME=dc1
     - SKIP_PSWATCH=true
    ports:
     - 8888:80
    external_links:
     - consul:consul
     - carbon:carbon
    volumes_from:
     - carbon
    privileged: true

logger:
  image: qnib/logger
  dns: 127.0.0.1
  hostname: logger
  container_name: logger
  ports:
   - "5514:5514"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - COLLECT_METRICS=true
  - CNT_TYPE=service
  external_links:
   - consul:consul
   - elasticsearch:elasticsearch
  privileged: true
