influxdb:
    hostname: influxdb
    container_name: influxdb
    dns: 127.0.0.1
    image: qnib/influxdb
    volumes:
     - /opt/influxdb/shared
    environment:
     - DC_NAME=dc1
    external_links:
     - consul:consul
    ports:
     - 4242:4242
     - 8083:8083
     - 8086:8086
    privileged: true
