consul:
   image: qnib/consul
   hostname: consul
   container_name: consul
   ports:
    - "8500:8500"
    - "8400:8400"
    - "8302:8302/tcp"
    - "8302:8302/udp"
    - "8301:8301/tcp"
    - "8301:8301/udp"
    - "8300:8300"
   environment:
    - SERVICE_8500_NAME=consul-api
    - SERVICE_8400_NAME=consul-cli-rcp
    - SERVICE_8302_NAME=consul-wan
    - SERVICE_8301_NAME=consul-lan
    - SERVICE_8300_NAME=consul-srv-rpc
    - BOOTSTRAP_CONSUL=false
    - RUN_SERVER=true
    - DC_NAME=dc1

registrator:
   image: gliderlabs/registrator:latest
   hostname: registrator
   container_name: registrator
   volumes:
    - /var/run/docker.sock:/tmp/docker.sock
   
vmConsul:
   image: qnib/consul
   hostname: vmconsul
   container_name: vmconsul
   #dns: 127.0.0.1
   ports:
    - "18500:8500"
   environment:
    - SERVICE_8500_IGNORE=yes
    - WAN_SERVER=172.17.42.1
    - BOOTSTRAP_CONSUL=true
    - RUN_SERVER=true
    - SKIP_PSWATCH=true
    - PARENT_DC_NAME=dc1
 
zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    dns: 127.0.0.1
    image: qnib/zookeeper
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    environment:
    - ZK_DC=dc1
    - SERVICE_2181_NAME=zookeeper
    - SERVICE_2888_NAME=zookeeper-peerport
    - SERVICE_3888_NAME=zookeeper-leaderport
    - SKIP_PSWATCH=true
    volumes:
    - /srv/data/zookeeper/:/tmp/zookeeper/
    privileged: true

zkui:
    hostname: zkui
    container_name: zkui
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zkui
    ports:
    - 9090:9090
    environment:
    - ZK_DC=dc1
    - SKIP_PSWATCH=true
    privileged: true

kafka:
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/kafka
    ports:
    - 9092:9092
    - 54299:54299
    environment:
    - FORWARD_TO_KAFKA=true
    - SERVICE_9092_NAME=kafka
    - SERVICE_54299_NAME=jmxremote
    - SKIP_PSWATCH=true
    - ZK_DC=dc1
    privileged: true

kafkaMon:
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/kafka-monitor
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=true
    - RUN_SERVER=false
    - BOOTSTRAP_CONSUL=false
    - SKIP_PSWATCH=true
    ports:
    - 8080:8080
    privileged: true

influxdb:
    dns: 127.0.0.1
    image: qnib/influxdb
    volumes:
    - /opt/influxdb/shared
    environment:
     - SERVICE_4242_NAME=opentsdb
     - DC_NAME=dc1
     - SKIP_PSWATCH=true
    ports:
    - 4242:4242
    - 8083:8083
    - 8086:8086
    privileged: true

carbon:
    image: qnib/carbon
    dns: 127.0.0.1
    environment:
     - SERVICE_2003_NAME=carbon
     - FORWARD_TO_LOGSTASH=false
     - SKIP_PSWATCH=true
    ports:
     - 2003:2003

gapi:
    dns: 127.0.0.1
    image: qnib/graphite-api
    environment:
     - SKIP_PSWATCH=true
     - SERVICE_8888_NAME=graphite-api
    ports:
     - 8888:80
    privileged: true

grafana2:
    image: qnib/grafana2
    ports:
    - "3000:3000"
    dns: 127.0.0.1
    environment:
    - DC_NAME=dc1
    - SKIP_PSWATCH=true
    privileged: true
