es0:
    extends:
      file: base.yml
      service: es
    hostname: es0
    ports:
     - "9210:9200"
    environment:
    - ES_TAGS=es0
    external_links:
    - 1node3elasticsearch_consul_1:consul

es1:
    extends:
      file: base.yml
      service: es
    hostname: es1
    ports:
     - "9211:9200"
    environment:
    - ES_TAGS=es1
    external_links:
    - 1node3elasticsearch_consul_1:consul

es2:
    extends:
      file: base.yml
      service: es
    hostname: es2
    ports:
     - "9212:9200"
    environment:
    - ES_TAGS=es2
    external_links:
    - 1node3elasticsearch_consul_1:consul
