base:
    environment:
     - DC_NAME=dc1
     - COLLECT_METRICS=true
    dns: 127.0.0.1
    dns_search:
     - node.consul
     - service.consul

influxdb:
    extends:
      file: base.yml
      service: base
    image: qnib/influxdb
    volumes:
    - /opt/influxdb/shared
    ports:
    - 4242
    - 8083
    - 8086
