base:
    environment:
     - DC_NAME=dc1
     - COLLECT_METRICS=true
    dns: 127.0.0.1
    dns_search:
     - node.consul
     - service.consul
    privileged: true

kafka811:
    extends:
      file: base.yml
      service: base
    image: qnib/kafka:0.8.1.1
    environment:
     - FORWARD_TO_KAFKA=true
     - SKIP_PSWATCH=true

kafka821:
    extends:
      file: base.yml
      service: base
    image: qnib/kafka
    environment:
     - FORWARD_TO_KAFKA=true
     - SKIP_PSWATCH=true

kibana3:
    extends:
      file: base.yml
      service: base
    image: qnib/kibana3
    ports:
     - "80:80"
    environment:
     - FORWARD_TO_LOGSTASH=false
     - COLLECT_METRICS=false
     - SKIP_PSWATCH=true
    hostname: kibana3

logger:
    extends:
      file: base.yml
      service: base
    image: qnib/logstash
    ports:
     - "5514:5514"
    environment:
     - FORWARD_TO_LOGSTASH=false
     - COLLECT_METRICS=false
     - SKIP_PSWATCH=true
    hostname: logger

elasticsearch:
    extends:
      file: base.yml
      service: base
    image: qnib/es-kopf
    environment:
     - ES_CLUSTER_NAME=qnib2015
     - FORWARD_TO_LOGSTASH=false
     - COLLECT_METRICS=false
     - SKIP_PSWATCH=true
    hostname: elasticsearch
    volumes:
     - /var/lib/elasticsearch
