golang:
    hostname: golang
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/golang
    environment:
     - DC_NAME=dc1
     - BOOTSTRAP_CONSUL=false
     - RUN_SERVER=false
     - SKIP_PSWATCH=true
    volumes:
     - ./src/:/root/src/
    external_links:
    - dockerhost_consul_1:consul
    privileged: true

zkui:
    hostname: zkui
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zkui
    environment:
    - DC_NAME=dc1
    links:
    - zookeeper:zookeeper
    external_links:
    - dockerhost_consul_1:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper:
    hostname: zookeeper
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zookeeper
    environment:
    - DC_NAME=dc1
    external_links:
    - dockerhost_consul_1:consul
    privileged: true

kafkaMonitor:
    image: qnib/kafka-monitor
    hostname: kafka-monitor
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    environment:
    - DC_NAME=dc1
    - FORWARD_TO_KAFKA=false
    external_links:
    - dockerhost_consul_1:consul
    links:
    - kafka0:kafka
    ports:
    - 18080:8080
    privileged: true

kafkaMgr:
    image: qnib/kafka-manager
    hostname: kafka-manager
    dns: 127.0.0.1
    dns_search:
     - node.consul
    environment:
     - DC_NAME=dc1
     - BOOTSTRAP_CONSUL=false
     - RUN_SERVER=false
    external_links:
    - dockerhost_consul_1:consul
    links:
     - kafka0:kafka
    ports:
     - 19000:9000
    privileged: true
    
kafka0:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka0
    environment:
    - DC_NAME=dc1
    - BARE_HOST=kafka0
    external_links:
    - dockerhost_consul_1:consul
    links:
    - zookeeper:zookeeper

kafka1:
    extends:
      file: base.yml
      service: kafka
    environment:
    - DC_NAME=dc1
    - BARE_HOST=kafka1
    hostname: kafka1
    external_links:
    - dockerhost_consul_1:consul
    links:
    - zookeeper:zookeeper

kafka2:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka2
    environment:
    - DC_NAME=dc1
    - BARE_HOST=kafka2
    external_links:
    - dockerhost_consul_1:consul
    links:
    - zookeeper:zookeeper

kafka3:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka3
    environment:
    - DC_NAME=dc1
    - BARE_HOST=kafka3
    external_links:
    - dockerhost_consul_1:consul
    links:
    - zookeeper:zookeeper


kafka4:
    extends:
      file: base.yml
      service: kafka
    hostname: kafka4
    environment:
    - DC_NAME=dc1
    - BARE_HOST=kafka4
    external_links:
    - dockerhost_consul_1:consul
    links:
    - zookeeper:zookeeper

heka:
    image: qnib/heka
    hostname: heka
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    ports:
    - 4352:4352
    environment:
    - FORWARD_TO_HEKA=false
    - DC_NAME=dc1
    - BOOTSTRAP_CONSUL=false
    - RUN_SERVER=false
    external_links:
    - dockerhost_consul_1:consul
    volumes:
    - /proc/stat:/host/proc/stat:ro
    - /sys/block/sda/stat:/host/sys/block/sda/stat:ro
    - /proc/meminfo:/host/proc/meminfo:ro
    - /proc/loadavg:/host/proc/loadavg:ro
    - ./etc/heka/:/etc/heka/
