consul:
    extends:
      file: base.yml
      service: base
    hostname: consul
    container_name: consul
    image: qnib/consul
    environment:
     - RUN_SERVER=true
     - BOOTSTRAP_CONSUL=true
    ports:
     - "8500:8500"

golang:
    extends:
      file: base.yml
      service: base
    hostname: golang
    container_name: golang
    image: qnib/golang
    volumes:
     - ./src/:/root/src/
    links:
    - consul:consul

zkui:
    extends:
      file: base.yml
      service: base
    hostname: zkui
    container_name: zkui
    image: qnib/zkui
    links:
    - zookeeper:zookeeper
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper:
    extends:
      file: base.yml
      service: base
    hostname: zookeeper
    container_name: zookeeper
    image: qnib/zookeeper
    links:
    - consul:consul

kafkaMonitor:
    extends:
      file: base.yml
      service: base
    image: qnib/kafka-monitor
    hostname: kafka-monitor
    container_name: kafka-monitor
    environment:
     - FORWARD_TO_KAFKA=false
    links:
     - consul:consul
     - kafka0:kafka
    ports:
     - 18080:8080

kafkaMgr:
    extends:
      file: base.yml
      service: base
    image: qnib/kafka-manager
    hostname: kafka-manager
    container_name: kafka-manager
    links:
     - consul:consul
     - kafka0:kafka
    ports:
     - 19000:9000
    
kafka0:
    extends:
      file: base.yml
      service: kafka811
    environment:
    - BARE_HOST=kafka0
    - KAFKA_MIN_INSTANCES=3
    - KAFKA_BOOTSTRAP_TOPICS=syslog:2,ring0:3,ring1:3,ring2:3,ring3:3,ring4:3,ring5:3,final:3
    hostname: kafka0
    container_name: kafka0
    links:
     - zookeeper:zookeeper
     - consul:consul

kafka1:
    extends:
      file: base.yml
      service: kafka811
    environment:
    - BARE_HOST=kafka1
    hostname: kafka1
    container_name: kafka1
    links:
     - zookeeper:zookeeper
     - consul:consul

kafka2:
    extends:
      file: base.yml
      service: kafka811
    hostname: kafka2
    container_name: kafka2
    environment:
    - BARE_HOST=kafka2
    links:
     - zookeeper:zookeeper
     - consul:consul

kafka3:
    extends:
      file: base.yml
      service: kafka811
    hostname: kafka3
    container_name: kafka3
    environment:
     - BARE_HOST=kafka3
    links:
     - zookeeper:zookeeper
     - consul:consul

heka:
    extends:
      file: base.yml
      service: base
    image: qnib/heka
    hostname: heka
    container_name: heka
    ports:
    - 14352:4352
    environment:
    - FORWARD_TO_HEKA=false
    - SUPERVISOR_SKIP_SRV=heka
    links:
    - consul:consul
    volumes:
    - ./opt/qnib/heka/bin/:/opt/qnib/heka/bin/
    - ./heka/etc/:/etc/heka/
    - ./heka/lua/:/usr/share/heka/lua/
