consul:
    image: qnib/consul
    ports:
     - "8500"
    environment:
    - DC_NAME=guido
    - RUN_SERVER=true
    - BOOTSTRAP_CONSUL=true
    hostname: consul
    dns: 127.0.0.1
    privileged: true

zkui:
    hostname: zkui
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zkui
    environment:
    - DC_NAME=guido
    links:
    - zookeeper:zookeeper
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper:
    hostname: zookeeper
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    image: qnib/zookeeper
    environment:
    - DC_NAME=guido
    links:
     - consul:consul
    privileged: true

kafkaMonitor:
    image: qnib/kafka-monitor
    hostname: kafka-monitor
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    environment:
    - DC_NAME=guido
    - FORWARD_TO_KAFKA=false
    external_links:
    - dockerhost_consul_1:consul
    links:
     - consul:consul
     - kafka0:kafka
    ports:
    - 18080:8080
    privileged: true

kafkaMgr:
    image: qnib/kafka-manager
    hostname: kafka-manager
    dns: 127.0.0.1
    dns_search:
     - node.consul
    environment:
     - DC_NAME=guido
     - BOOTSTRAP_CONSUL=false
     - RUN_SERVER=false
    links:
     - consul:consul
     - kafka0:kafka
    ports:
     - 19000:9000
    privileged: true
    
kafka0:
    extends:
      file: base.yml
      service: kafka811
    environment:
    - DC_NAME=guido
    - BARE_HOST=kafka0
    - KAFKA_MIN_INSTANCES=3
    - KAFKA_BOOTSTRAP_TOPICS=syslog:2,ring0:3,ring1:3,ring2:3,ring3:3,ring4:3,ring5:3,final:3
    hostname: kafka0
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka1:
    extends:
      file: base.yml
      service: kafka811
    environment:
    - DC_NAME=guido
    - BARE_HOST=kafka1
    hostname: kafka1
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka2:
    extends:
      file: base.yml
      service: kafka811
    hostname: kafka2
    environment:
    - DC_NAME=dguido
    - BARE_HOST=kafka2
    links:
    - consul:consul
    - zookeeper:zookeeper

kafka3:
    extends:
      file: base.yml
      service: kafka811
    hostname: kafka3
    environment:
    - DC_NAME=dc1
    - BARE_HOST=kafka3
    links:
    - consul:consul
    - zookeeper:zookeeper

