consul:
    image: qnib/consul
    ports:
     - "8500:8500"
    dns: 127.0.0.1
    hostname: consul
    privileged: true

terminal:
    image: qnib/terminal
    dns: 127.0.0.1
    hostname: terminal
    privileged: true
    links:
    - consul:consul
