consul:
    image: qnib/consul
    hostname: consul
    container_name: consul
    ports:
     - 53:53/udp
     - 53:53/tcp
    dns: 127.0.0.1
    environment:
     - DC_NAME=dc1
     - BOOTSTRAP_CONSUL=true
     - RUN_SERVER=true
    ports:
     - "8500:8500"
statsd:
  image: qnib/statsd
  ports:
   - "8125"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - COLLECT_METRICS=true
  - CNT_TYPE=service
  dns: 127.0.0.1
  hostname: statsd
  container_name: statsd
  privileged: true
  links:
   - consul:consul

carbon:
  image: qnib/carbon
  ports:
   - "2003:2003"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - COLLECT_METRICS=true
  - CNT_TYPE=service
  - CARBON_METRICS_ENTRY=true
  volumes:
  - /var/lib/carbon/whisper/
  dns: 127.0.0.1
  hostname: carbon
  container_name: carbon
  privileged: true
  links:
   - consul:consul

gapi:
  image: qnib/graphite-api
  ports:
  - 8888:80
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - COLLECT_METRICS=true
  - CNT_TYPE=service
  dns: 127.0.0.1
  hostname: graphite-api
  container_name: graphite-api
  privileged: true
  links:
   - consul:consul
  volumes_from:
   - carbon

grafana:
  image: qnib/grafana
  ports:
   - "81:80"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - COLLECT_METRICS=true
  - CNT_TYPE=service
  - SUPERVISOR_SKIP_SRV=dashboard
  dns: 127.0.0.1
  hostname: grafana
  container_name: grafana
  privileged: true
  volumes:
   - ./var/www/grafana/app/dashboards/:/var/www/grafana/app/dashboards/
  links:
   - consul:consul

kopf:
  image: qnib/kopf
  hostname: kopf
  container_name: kopf
  dns: 127.0.0.1
  ports:
   - 8088:80
  environment:
   - DC_NAME=dc1
   - FORWARD_TO_LOGSTASH=false
   - COLLECT_METRICS=false
   - SKIP_PSWATCH=true
   - SERVICE_8088_NAME=es-kopf
   - BOOTSTRAP_CONSUL=false
   - RUN_SERVER=false
  links:
   - consul:consul


kibana3:
  image: qnib/kibana3
  ports:
   - "80:80"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - CNT_TYPE=service
  - SKIP_PSWATCH=true
  - COLLECT_METRICS=false
  - HTTPPORT=9210
  dns: 127.0.0.1
  hostname: kibana3
  container_name: kibana3
  privileged: true
  volumes:
   - ./dash/kibana3/:/var/www/kibana/app/dashboards/
  links:
  - consul:consul

kibana4:
  image: qnib/kibana4
  ports:
   - "5601:5601"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - CNT_TYPE=service
  - SKIP_PSWATCH=true
  - COLLECT_METRICS=false
  - ES_URL=http://meta.elasticsearch.service.consul:9200
  dns: 127.0.0.1
  hostname: kibana4
  container_name: kibana4
  privileged: true
  links:
  - consul:consul


logstash:
    image: qnib/logger
    hostname: logger
    container_name: logger
    dns: 127.0.0.1
    ports:
     - 5514:5514
    dns_search:
    - node.consul
    - service.consul
    environment:
    - FORWARD_TO_HEKA=false
    - DC_NAME=dc1
    - BOOTSTRAP_CONSUL=false
    - RUN_SERVER=false
    links:
    - consul:consul
    volumes:
    - ./logstash/meta/etc/:/etc/logstash/conf.d/
    - ./logstash/bin:/usr/local/logstash/bin/

heartbeat:
    image: qnib/logger
    hostname: heartbeat
    container_name: heartbeat
    dns: 127.0.0.1
    dns_search:
    - node.consul
    - service.consul
    environment:
    - FORWARD_TO_HEKA=false
    - DC_NAME=dc1
    - BOOTSTRAP_CONSUL=false
    - RUN_SERVER=false
    - SUPERVISOR_START_EXTERNAL=/usr/local/logstash/bin/query_hb.sh
    links:
    - consul:consul
    volumes:
    - ./logstash/heartbeat/etc/:/etc/logstash/conf.d/
    - ./logstash/bin:/usr/local/logstash/bin/

es-lb:
  image: qnib/es-lb
  dns: 127.0.0.1
  hostname: es-lb
  container_name: es-lb
  ports:
   - "9210:9200"
  links:
   - consul:consul
  environment:
   - DC_NAME=dc1

elasticsearch:
    image: qnib/elasticsearch:1.7
    dns: 127.0.0.1
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
     - "9200:9200"
    environment:
    - DC_NAME=dc1
    - ES_CLUSTER_NAME=meta
    - FORWARD_TO_LOGSTASH=false
    - COLLECT_METRICS=false
    - SKIP_PSWATCH=true
    - ES_TAGS=meta
    - BOOTSTRAP_CONSUL=false
    - RUN_SERVER=false
    volumes:
    - /var/lib/elasticsearch
    links:
       - consul:consul
    privileged: true

