consul:
    image: qnib/consul
    ports:
     - "8500:8500"
    hostname: consul
    dns: 127.0.0.1
    privileged: true
    environment:
     - RUN_SERVER=true
     - BOOTSTRAP_CONSUL=true

mongodb:
    image: qnib/mongodb
    dns: 127.0.0.1
    hostname: mongodb
    ports:
     - "27017:27017"
     - "28017:28017"
    links:
     - consul:consul
    environment:
     - MONGO_RESTORE=/backup/rocketchat_init.tar
    privileged: true

rocketchat:
    image: qnib/rocketchat
    dns: 127.0.0.1
    hostname: rocketchat
    ports:
     - "3000:3000"
    links:
     - consul:consul
     - mongodb:db
    privileged: true
