consul:
    image: qnib/consul
    ports:
     - "8500:8500"
    hostname: consul
    dns: 127.0.0.1
    privileged: true

terminal:
    image: qnib/rocketchat
    dns: 127.0.0.1
    hostname: rocketchat
    links:
     - consul:consul
    ports:
     - 27017:27017
     - 3000:3000
    privileged: false
