[hekad]
maxprocs = 4

##### INPUT
[ProcStats]
type = "FilePollingInput"
ticker_interval = 5
file_path = "/host/proc/stat"
decoder = "ProcStatDecoder"

[StatAccumInput]

[ProcStatDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_procstat.lua"

[ProcStatFilter]
type = "SandboxFilter"
filename = "lua_filters/procstat.lua"
preserve_data = true
message_matcher = "Type == 'stats.procstat'"
[ProcStatFilter.config]
    whitelist = "cpu$"
    extras = true
    percent_integer = true

[demo_counter]
type = "SandboxFilter"
message_matcher = "Type == 'heka.sandbox.procstat'"
ticker_interval = 5
filename = "my_lua/increment.lua"

preserve_data = true
##### OUTPUT
[RstEncoder]

[LogOutput]
message_matcher = "TRUE"
#ype != 'stats.procstat'"
encoder = "RstEncoder"

#[WhisperOutput]
#base_path = "/tmp/"
#message_matcher = "Type == 'heka.sandbox-output'"
#default_agg_method = 3
#default_archive_info = [ [0, 30, 1440] ]
#folder_perm = "755"