consul:
   image: qnib/consul
   hostname: consul
   container_name: consul
   #dns: 127.0.0.1
   ports:
    - "8500:8500"
    - "8400:8400"
    - "8302:8302/tcp"
    - "8302:8302/udp"
    - "8301:8301/tcp"
    - "8301:8301/udp"
    - "8300:8300"
   environment:
    - SERVICE_8500_NAME=consul-api
    - SERVICE_8400_NAME=consul-cli-rcp
    - SERVICE_8302_NAME=consul-wan
    - SERVICE_8301_NAME=consul-lan
    - SERVICE_8300_NAME=consul-srv-rpc
    - BOOTSTRAP_CONSUL=false
    - RUN_SERVER=true
    - DC_NAME=dc1

registrator:
   image: gliderlabs/registrator:latest
   hostname: registrator
   container_name: registrator
   volumes:
    - /var/run/docker.sock:/tmp/docker.sock
   
vmConsul:
   image: qnib/consul
   hostname: vmconsul
   container_name: vmconsul
   #dns: 127.0.0.1
   ports:
    - "18500:8500"
   environment:
    - SERVICE_8500_IGNORE=yes
    - WAN_SERVER=172.17.42.1
    - BOOTSTRAP_CONSUL=true
    - RUN_SERVER=true
 
