base:
   dns: 127.0.0.1
   dns_search:
    - node.consul
    - service.consul

consul:
   image: qnib/consul
   ports:
    - "8500:8500"
    - "8400:8400"
    - "8302:8302/tcp"
    - "8302:8302/udp"
    - "8301:8301/tcp"
    - "8301:8301/udp"
    - "8300:8300"
   environment:
    - SERVICE_8500_NAME=consul-api
    - SERVICE_8400_NAME=consul-cli-rcp
    - SERVICE_8302_NAME=consul-wan
    - SERVICE_8301_NAME=consul-lan
    - SERVICE_8300_NAME=consul-srv-rpc
    - RUN_SERVER=true
    - DC_NAME=dc1
   
vmConsul:
   image: qnib/consul
   environment:
    - WAN_SERVER=172.17.42.1
    - BOOTSTRAP_CONSUL=true
    - RUN_SERVER=true
 

