grafana:
  extends: 
    file: base.yml
    service: grafana

#elasticsearch:
#  extends:
#    file: base.yml
#    service: elasticsearch
#  links:
#  - consul:consul

esm0:
  extends:
    file: base.yml
    service: elasticsearch
  hostname: esm0
  links:
  - consul:consul
  ports:
  - "9200:9200"
  environment:
  - ES_DATA_NODE=false

esm1:
  extends:
    file: base.yml
    service: elasticsearch
  ports:
  - "9201:9200"
  hostname: esm1
  links:
  - consul:consul
  environment:
  - ES_DATA_NODE=false

esd:
  extends:
    file: base.yml
    service: elasticsearch
  links:
  - consul:consul
  environment:
  - ES_MASTER_NODE=false

kibana:
  extends:
    file: base.yml
    service: kibana3
  links:
  - consul:consul
  - esm0:esm0

kibana4:
  extends:
    file: base.yml
    service: kibana4
  links:
  - consul:consul
  - esm0:esm0

kopf: 
  extends:
    file: base.yml
    service: kopf

logger:
  extends:
    file: base.yml
    service: logger
  links:
  - consul:consul

carbon:
  extends:
    file: base.yml
    service: carbon
  links:
  - consul:consul

gapi:
  extends:
    file: base.yml
    service: gapi
  links:
  - consul:consul
  - carbon:carbon
  volumes_from:
   - carbon

consul:
  extends:
    file: base.yml
    service: consul

kafka:
  extends:
    file: base.yml
    service: kafka
  links:
  - consul:consul
  

